
const projectData = [
  {
    id: 1,
    title: "Shopping Website",
    subtitle: "Headphone shopping",
    description: "This is a sample shopping website with a shopping cart.",
    link: "https://razieh-abedi.github.io/shopping-cart/",
  },
  {
    id: 2,
    title: "Review App",
    subtitle: "Customer Reviews",
    description: "This is a sample app showing customers'reviews.",
    link: "https://razieh-abedi.github.io/reviews/",
  },
  {
    id: 3,
    title: "Shopping Website",
    subtitle: "Furniture shopping",
    description: "This is a sample shopping website with a shopping cart.",
    link: "https://razieh-abedi.github.io/furniture-shopping-website/",
  },
  {
    id: 4,
    title: "Calculator",
    subtitle: "BMI Calculator",
    description: "This is an application to calculate BMI.",
    link: "https://razieh-abedi.github.io/BMI-calculator/",
  },
  {
    id: 5,
    title: "To Do App",
    subtitle: "To Do List application",
    description: "This is an application to organize tasks in a to-do list.",
    link: "https://github.com/Razieh-Abedi/to-do-list-mini-app",
  },
  {
    id: 6,
    title: "Tours App",
    subtitle: "Choosing Tours Application",
    description: "This is an application to choose the tours for travel.",
    link: "https://razieh-abedi.github.io/tours/",
  },
  {
    id: 7,
    title: "Convertor App",
    subtitle: "Unit Convertor Application",
    description: "This is an application to convert measurement units.",
    link: "https://razieh-abedi.github.io/Unit-convertor/",
  },
  {
    id: 8,
    title: "Shopify Website",
    subtitle: "Shopify Template",
    description: "This is a sample template for Shopify Website.",
    link: "https://razieh-abedi.github.io/Shopify-website-template/",
  },
  {
    id: 9,
    title: "Forms",
    subtitle: "Validated Forms",
    description: "This is a sample validated form.",
    link: "https://razieh-abedi.github.io/validated-form-sample/",
  },
  {
    id: 10,
    title: "Portfolio",
    subtitle: "Portfolio Website",
    description: "This is a sample portfolio website for a web developer.",
    link: "https://razieh-abedi.github.io/portfolio/",
  },
  {
    id: 11,
    title: "Slider Project",
    subtitle: "Timing Slider",
    description: "This is a timer slider for a construction website.",
    link: "https://razieh-abedi.github.io/timing-slider/",
  },
  {
    id: 12,
    title: "Risa Website",
    subtitle: "Risa right-to-left Website",
    description: "This is a website of product website.",
    link: "https://razieh-abedi.github.io/right-to-left-website-template/",
  },
  {
    id: 13,
    title: "Hotel Website",
    subtitle: "Tubotel Website",
    description: "This is a website of a hotel.",
    link: "https://tubotel.com/",
  },
];

export default projectData;
